In [33]:
from parser import TestTableParser
import pandas as pd

testTableParser = TestTableParser()
xlsx = pd.ExcelFile('file1.xlsx')
names = xlsx.sheet_names
sheet_to_df_map = {}
for i in range(len(names)):
	sheet_to_df_map[names[i]] = testTableParser.all_action(
		pd.read_excel(open('file1.xlsx', 'rb'), header=None, sheet_name=names[i]))

print(xlsx.sheet_names)
sheet_to_df_map.get('TDSheet')[0]

False
['TDSheet']

,nan,"ПАО ""Птицефабрика ""Боровская""",Цех №2__Птичник: Пт № 16,Цех №2__Птичник: Пт № 16,Показатели__ЕдИзм,Дата на начало периода__ЕдИзм,Наличие кур-несушек\nна начало периода__гол.,Пало__норм__гол.,Пало__факт__гол.,Пало__норм__%,...,Среднемесячное поголовье__факт__гол.,Яиц на начальную\nкурицу-несушку__норм__шт.,Яиц на начальную\nкурицу-несушку__факт__шт.,Яиц на среднюю\nкурицу-несушку__норм__шт.,Яиц на среднюю\nкурицу-несушку__факт__шт.,Яйценоскость__норм__%,Яйценоскость__факт__%,Средний вес 1-ой головы__факт__кг,Однородность %__факт__кг,Средний вес 1-го яйца__факт__г
3,NaN,Показатели продуктивного периода 1 Марта 201...,NaN,NaN,NaN,01.03.2016,24490,98,10,0.4,...,875,20.2,0.68,21.0,18.93,75.0,67.62,2.018,75.0,65.6
4,NaN,NaN,NaN,NaN,NaN,02.03.2016,24486,98,4,0.4,...,875,20.2,0.69,21.0,19.35,75.0,69.1,2.018,75.0,65.6
5,NaN,NaN,NaN,NaN,NaN,03.03.2016,24474,98,12,0.4,...,874,20.2,0.68,21.0,18.95,75.0,67.66,2.018,75.0,65.6
6,NaN,NaN,NaN,NaN,NaN,04.03.2016,24470,122,4,0.5,...,874,18.1,0.67,19.0,18.74,67.86,66.94,2.018,75.0,65.6
7,NaN,NaN,NaN,NaN,NaN,05.03.2016,24469,122,1,0.5,...,874,18.1,0.67,19.0,18.74,67.86,66.94,2.018,75.0,65.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,NaN,NaN,NaN,NaN,NaN,10.12.2018,29999,150,10,0.5,...,1071,18.1,0.73,19.0,16.8,67.86,60.0,1.93,80.0,<NA>
923,NaN,NaN,NaN,NaN,NaN,11.12.2018,29995,150,4,0.5,...,1071,18.1,0.71,19.0,16.13,67.86,57.61,1.93,80.0,<NA>
924,NaN,NaN,NaN,NaN,NaN,12.12.2018,18092,90,5,0.5,...,646,18.1,0.65,19.0,24.51,67.86,87.55,1.93,80.0,<NA>
925,NaN,NaN,NaN,NaN,NaN,13.12.2018,7119,107,7,1.5,...,254,17.0,0.29,18.0,27.61,64.29,98.61,1.93,80.0,<NA>
926,NaN,NaN,NaN,NaN,NaN,14.12.2018,<NA>,<NA>,19,1.5,...,<NA>,17.0,0.24,18.0,<NA>,64.29,<NA>,1.93,80.0,<NA>